language: generic
dist: bionic
os: linux
env:
  global:
    - DEVKITPRO=$HOME
    - DEVKITARM=$DEVKITPRO/devkitARM
addons:
  apt:
    packages:
      - gcc-multilib
      - linux-libc-dev
      - zlib1g-dev
cache:
  apt: true
install:
  - pushd $HOME
  - travis_retry wget https://github.com/devkitPro/buildscripts/releases/download/devkitARM_r52/devkitARM_r52-linux.tar.xz
  - tar xJf devkitARM*.tar.xz
  - travis_retry wget https://github.com/devkitPro/devkitarm-rules/releases/download/v1.0.0/devkitarm-rules-1.0.0.tar.xz
  - tar xJf devkitarm-rules-*.tar.xz -C $DEVKITARM
  - popd
jobs:
  include:
    - os: linux
      env: _="Build"
      script:
            - sh build.sh
            - make clean
            - make all
