name: GithubCI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build-devkitARM:
    runs-on: ubuntu-latest
    steps:
      # apparently setting an env var in a step will not take effect until the next step, so when setting env vars one cannot depend on vars set previously but in the same step
      - name: Set environment variables
        run: |
          echo "DEVKITPRO=$HOME" >> $GITHUB_ENV
          echo "DEVKITARM=$HOME/devkitARM" >> $GITHUB_ENV
      
      - name: Load and setup devkitARM
        run: |
          wget -nv https://github.com/devkitPro/buildscripts/releases/download/devkitARM_r52/devkitARM_r52-linux.tar.xz https://github.com/devkitPro/devkitarm-rules/releases/download/v1.0.0/devkitarm-rules-1.0.0.tar.xz
          tar xJf devkitARM*.tar.xz -C $DEVKITPRO
          tar xJf devkitarm-rules-*.tar.xz -C $DEVKITARM
      
      - name: Fetch repo
        uses: actions/checkout@master
        
      - name: Build via script
        run: sh build.sh
      - name: Build via Makefile
        run: |
          make clean
          make -j$(nproc) all


  build-arm-none-eabi:
    runs-on: ubuntu-latest
    steps:
      - name: Install binutils-arm-none-eabi for devkitARM-less build
        run: sudo apt install binutils-arm-none-eabi
      
      - name: Fetch repo
        uses: actions/checkout@master
        
      - name: Build via script
        run: sh build.sh
      - name: Build via Makefile
        run: |
          make clean
          make -j$(nproc) all
